Update release action

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -111,6 +111,9 @@ jobs:
             if [ "$(printf '%s\n' "$MAX_TAG" "$CURRENT_TAG" | sort -V | tail -1)" = "$CURRENT_TAG" ] && [ "$MAX_TAG" != "$CURRENT_TAG" ]; then
               echo "publish=true" >> $GITHUB_OUTPUT
               echo "Current tag $CURRENT_TAG is greater than max tag $MAX_TAG"
+            elif [ "$MAX_TAG" = "$CURRENT_TAG" ]; then
+              echo "publish=update" >> $GITHUB_OUTPUT
+              echo "Current tag $CURRENT_TAG is the same as max tag $MAX_TAG, may need to update published version"
             else
               echo "publish=false" >> $GITHUB_OUTPUT
               echo "Current tag $CURRENT_TAG is not greater than max tag $MAX_TAG, skipping publish"
@@ -118,7 +121,7 @@ jobs:
           fi
 
       - name: Setup Rebar3
-        if: steps.should_publish.outputs.publish == 'true'
+        if: steps.should_publish.outputs.publish != 'false'
         uses: erlef/setup-beam@v1
         with:
           # Latest that excludes pre-releases
@@ -130,7 +133,7 @@ jobs:
             https://cdn.jsdelivr.net/hex
 
       - name: Publish to Hex.pm
-        if: steps.should_publish.outputs.publish == 'true'
+        if: steps.should_publish.outputs.publish != 'false'
         env:
           HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
         run: |
@@ -142,14 +145,17 @@ jobs:
           TODAY=$(date +%Y-%m-%d)
 
           # Check if the package was already published today
-          REPLACE=$(if mix hex.info "$APP" "$VERSION" 2>&1 | grep -q "Released: $TODAY"; then echo " --replace"; fi)
+          REPLACE=$(if mix hex.info "$APP" "$VERSION" 2>&1 | grep -q "Released: $TODAY"; then echo " replace"; fi)
 
           if [ -n "$REPLACE" ]; then
-            echo "Package $APP $VERSION was released today, using --replace flag"
-          else
+            echo "Package $APP $VERSION was released today, trying to update existing release"
+            rebar3 hex publish --repo hexpm --yes --replace
+          elif [ "${{ steps.should_publish.outputs.publish }}" = "true" ]; then
             echo "Publishing $APP $VERSION"
+            rebar3 hex publish --repo hexpm --yes
+          else
+            echo "Package $APP $VERSION was already published and cannot be replaced!" && exit 1
           fi
-          rebar3 hex publish --repo hexpm --yes $REPLACE
 
       - name: Retire prior version
         if: steps.should_publish.outputs.publish == 'true'
